"""create tables

Revision ID: f1daac12d02e
Revises: 
Create Date: 2024-09-01 17:31:53.606600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1daac12d02e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispositivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuários',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cartões',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('id_usuário', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_usuário'], ['usuários.id'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('acessos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id_cartão', sa.Integer(), nullable=False),
    sa.Column('id_dispositivo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cartão'], ['cartões.uid'], ),
    sa.ForeignKeyConstraint(['id_dispositivo'], ['dispositivos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('acessos')
    op.drop_table('cartões')
    op.drop_table('usuários')
    op.drop_table('dispositivos')
    # ### end Alembic commands ###
